#!/bin/bash

bluetoothctl paired-devices | awk 'BEGIN {IGNORECASE = 1} $3$4$5$6$7$8$9$10$11$12  ~ "" {print "\n\033[1;32mMAC ADDRESS: \033[1;34m" $2 "\n\033[1;032mDEVICE NAME: \033[0m" $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " $19 " " $20}'
echo
