#!/bin/bash
spinner() {
    local i sp n
    sp='/-\|'
    ps="]"
    n=${#sp}
    nx=${#ps}
    while sleep 0.1; do
        printf "\033[1;33m%s\b\b\b\b\b" "[ ${sp:i++%n:1} ]"
    done
}

bluetoothctl scan on > /dev/null &

printf '\n\033[1;32m[SCANNING FOR DEVICES]: '
spinner &

sleep 6 
killall bluetoothctl
kill "$!" # kill the spinner
printf "\033[1;34m%s\b\b\b" "[COMPLETED]"
echo -e "\n"
exit
