#!/bin/bash

vol_changed=0

for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
do
    if [ $(pamixer --get-volume) -gt 95 ]; then
		break
	else
        vol_changed=1
		pactl set-sink-volume $SINK +5%
        cur_vol=$(pamixer --get-volume)
	fi
done

if [ $vol_changed == 1 ]; then
    dunstify -u normal "$(pamixer --get-volume)%" -r "169550" -I /usr/share/icons/Papirus-Dark/16x16/actions/audio-volume-high.svg
    paplay /usr/share/sounds/freedesktop/stereo/bell.oga
else
    dunstify -u normal "$(pamixer --get-volume)%" -r "169550" -I /usr/share/icons/Papirus-Dark/16x16/actions/audio-volume-high.svg
fi
