#!/bin/bash

vol_changed=0

for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
do
    vol_changed=1
	pactl set-sink-volume $SINK -5%
done

if [ $vol_changed == 1 ]; then
    dunstify -u normal "$(pamixer --get-volume)%" -r "169550" -I /usr/share/icons/Papirus-Dark/16x16/actions/audio-volume-medium.svg
else
    dunstify -u normal "$(pamixer --get-volume)%" -r "169550" -I /usr/share/icons/Papirus-Dark/16x16/actions/audio-volume-low.svg
fi
